### ISSUE TITLE
Syntax error on controller.py

### ISSUE THREAD

**Issue by darthjuanan** [oddworldng/cmsysbot-telegram#19]
## Expected Behavior

When I try to run, I get:

## Actual Behavior

cmsysbot/controller/controller.py", line 55
    with_subsections.append(f"^{section.name}$")
                                              ^
SyntaxError: invalid syntax

## Steps to Reproduce the Problem

I run with python 3.5.3:

python3 -m  cmsysbot -c config/config.json

**Comment by davafons** [comment]
The code uses some Python features like f-strings or type hinting, which are only available on __Python 3.6.x or greater__.

Take note that if you're using __Ubuntu 16.04__, the default version installed (and I guess that the one used by `virtualenv` by default) is __Python 3.5__

Thanks for the feedback, we will update the README to point that >=Python 3.6 is required.
